### ISSUE TITLE
Verify `src/rust` samples are valid by compiling them

### ISSUE THREAD

**Issue by Vektah** [Vektah/idea-rust#30]
This ensures we don't bend the grammar to invalid code.

**Comment by asheb** [comment]
I think we should write it in java (like other tests), probably inside `ParserTest.doTest` method (within those tests, not separately).

**Comment by Vektah** [comment]
The only downside to that is when iterating on grammar you need to wait for the compile - but if it is fast enough (say < 1s) then its definitely the way to go.

**Comment by asheb** [comment]
I'm switching to this one for now.
Ok, then maybe a single test for testing them all and returning a list of failed files.

BTW, how do you run a single test for iterating? Any special options?
I've only managed to run them all through Gradle.

**Comment by asheb** [comment]
Well, with `parse-only` it works pretty fast :)

**Comment by asheb** [comment]
Switching back to #29 to make parser pass the tests.

**Comment by Vektah** [comment]
Could you submit a PR so we can close this? Or is it still WIP?

**Comment by asheb** [comment]
Still WIP: some updated tests are not supported by parser yet.
